/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package juiceshop.api.automation;

import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

class AppTest {
    @Test
    void assert1Is1() {
        assertThat(1, is(1));
    }
}
