/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package juiceshop.api.automation.test;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import juiceshop.api.automation.domain.User;
import org.apache.http.HttpStatus;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.*;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.notNullValue;

class JuiceShopTest {

    @BeforeAll
    static void setup(){
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        baseURI="http://localhost:3000";
        basePath="/rest";
    }

    @Test
    void testListProducts() {
        when().
                get("/products/search").
                then().
                statusCode(HttpStatus.SC_OK).
                body("status",is("success")).
                body("data",notNullValue());
    }

    @Test
    void testLoginUser(){
        User user=new User("test18@test.com","password");
        given().
                contentType(ContentType.JSON).
                body(user).
                when().
                post("/user/login")
                .then().
                statusCode(HttpStatus.SC_OK)
                .body("authentication",notNullValue());
    }
}
